import React, { createContext, useState, useContext } from 'react';
import ukBanner from '../assets/uk_banner.png'
import plBanner from '../assets/pl_banner.png'

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');
  const translations = {
    en: {
      welcome: ukBanner,
      home: "Home",
      locations: "Locations",
      gastronomy: "Gastronomy",
      traditions: "Traditions",
      elderlyHomes: "Retirement Homes",
      aboutUs: "About Us",
      menuItems: {
        zakliczyn: "Zakliczyn",
        melsztyn: "Melsztyn",
        musicCenter: "Music Center",
        eurovelo: "Eurovelo Motesk",
        stIdzi: "St. Idzi",
      },
      zakliczyn: {
        title: "Zakliczyn",
        description: "Zakliczyn is a picturesque small town located in the southern part of Poland, known for its historical significance and scenic beauty. Here's a breakdown of key aspects:",
        title2: "Location:",
        text: "• Zakliczyn is situated in the Lesser Poland Voivodeship (Małopolskie), approximately 80 kilometers southeast of Kraków.",
        text2: "• It lies along the banks of the Dunajec River, within a region characterized by rolling hills and natural landscapes.",
        title3: "History:",
        text3: "• Zakliczyn's history dates back to the 14th century, with the first recorded mentions appearing in 1326.",
        text4: "• The town received its city rights in 1558, which spurred its economic and cultural growth.",
      },
      melsztyn: {
        title: "Melsztyn",
        description: " A Historical Village with Castle Ruins. Melsztyn is a charming village in the Lesser Poland region of Poland, primarily known for the ruins of its medieval castle. Here's an overview:",
        title2: "Location:",
        text: "• Melsztyn is located in the Lesser Poland Voivodeship, in southern Poland.",
        text2: "• It lies on the left bank of the Dunajec River.",
        text3: "• It is situated approximately 5 kilometers northwest of Zakliczyn, 25 kilometers southwest of Tarnów, and 64 kilometers east of the regional capital, Kraków.",
        title3: "Melsztyn Castle:",
        text4: "• The main attraction of Melsztyn is the ruins of Melsztyn Castle.",
        text5: "• This medieval castle has a rich history, dating back to the 14th century.",
        text6: "• The castle was the residence of Jan of Melsztyn.",
        text7: "• The ruins offer panoramic views of the surrounding landscape and are a popular spot for tourists and history enthusiasts.",
        text8: "• The castle ruins consist of a main tower, and the walls that surrounded it.",
        title4: "History:",
        text9: "• The village has a long history, closely tied to the castle.",
        text10: "• The castle played a significant role in the region's history.",
      },
      MusicCenter: {
        title: "Music Center",
        description: "The Krzysztof Penderecki European Centre for Music is a unique cultural institution located in Lusławice, in the Lesser Poland Voivodeship. Here are some key points about it:",
        title2: "Mission and Activities:",
        text: "• The center aims to develop the musical talents of young, gifted instrumentalists, vocalists, and conductors from around the world.",
        text2: "• It achieves this through master classes, workshops, concerts, and other artistic and educational events.",
        title3: "Location:",
        text3: "• The center is situated in Lusławice, near the place where Krzysztof Penderecki settled in 1976.",
        text4: "• Lusławice is located near Zakliczyn.",
        title4: "Architecture and Infrastructure:",
        text5: "• The heart of the center is a concert hall that can accommodate 650 listeners.",
        text6: "• The stage, which is 200 square meters, is designed for versatile use.",
        text7: "• Thanks to a movable orchestra pit, it is possible to stage operas and ballets.",
        text8: "• Next to the center is a beautiful arboretum, which is the work of Elżbieta and Krzysztof Penderecki.",
        title5: "Significance:",
        text9: "• The center is an important musical hub in Poland, promoting and supporting young talent.",
        text10: "• It is also a place that commemorates the legacy of one of Poland's most outstanding composers.",
      },
      EuroveloMotesk: {
        title: "Eurovelo Motesk",
        title2: "EuroVelo Routes:",
        text: "• EuroVelo is a network of long-distance cycling routes that crisscross Europe. These routes are designed to promote cycling tourism and provide infrastructure for cyclists.",
        text2: "• These routes are designed to allow exploration of Europe and it's varied landscapes.",
        title3: "Connection to Mostek and Zakliczyn:",
        text3: "• The region of Lesser Poland, where Mostek and Zakliczyn are located, is becoming increasingly popular for cycling tourism.",
        text4: "• The Dunajec River, which flows through this area, is a key feature that attracts cyclists. Rivers often provide relatively flat routes, making them ideal for cycling.",
        text5: "• It is very possible that Eurovelo routes run through this region, as they are designed to utilise existing infrastructure, and natural features.",
        text6: "• To get precise information of what Eurovelo route runs through those locations, I recommend visiting the official Eurovelo web page.",
      },
      StIdzi: {
        title: "St. Idzi",
        description: "The Church of St. Idzi (Saint Giles) in Zakliczyn is a significant historical and religious landmark. Here's information about it:",
        title2: "Historical Significance:",
        text: "• It's a Roman Catholic parish church located in the town of Zakliczyn, in the Lesser Poland Voivodeship.",
        text2: "• The church's history dates back to the medieval period.",
        text3: "• It has architectural elements from various periods, reflecting the town's historical development.",
        title3: "Religious Importance:",
        text4: "• It serves as the parish church for the local Catholic community.",
        text5: "• It is dedicated to Saint Giles (Idzi), a popular medieval saint.",
        title4: "Architectural Features:",
        text6: "• The church exhibits a mix of Gothic, Renaissance, and Baroque architectural styles.",
        text7: "• It has a characteristic tower.",
        text8: "• The interior contains historical religious artwork and artifacts.",
        title5: "Location:",
        text9: "• It's situated in the town of Zakliczyn, which is itself a town with a rich history.",

      },
      RetirementHomes: {
        title: "Retirement Homes",
        text1: "In Poland, retirement homes, also known as care homes or senior homes, play a crucial role in caring for the elderly. Here are some key aspects regarding these facilities:",
        title2: "Public Care Homes:",
        text3: "• Run by local governments.",
        text4: "• The costs of stay are partially funded by the state.",
        text5: "• Often have long wait lists.",
        title3: "Services Offered:",
        text7: "• 24-Hour Care: Assistance with daily activities, such as eating, dressing, and personal hygiene.",
        text8: "• Medical Care: Monitoring health conditions, administering medications, and rehabilitation.",
        text9: "• Nutrion: Balanced meals tailored to the needs of seniors.",
        text10: "• Recreation and Therapeutic Activities: Organized to activate seniors and improve their well-being.",
        text11: "• Psychological Care: Emotional support for residents.",
      },
      BakedBeans: {
        title: "Baked Beans",
        description: "Baked Beans is a popular and hearty dish from Polish cuisine, known for its rich flavor and simple preparation!",
        title2: "Ingredients",
        text: "• Beans (most often white)",
        text2: "• Sausage (preferably smoked)",
        text3: "• Smoked bacon",
        text4: "• Onion",
        text5: "• Garlic",
        text6: "• Tomato puree or canned tomatoes",
        text7: "• Spices: Marjoram, bay leaf, allspice, pepper, salt",
        title3: "Instructions",
        text8: "1. Soak the beans for several hours, then cook until soft.",
        text9: "2. Sauté the chopped onion, bacon and sausage in a pan.</div>",
        text10: "3. Add the garlic and spices, then the tomato puree or canned tomatoes.",
        text11: "4. Add the coocked beans to the sauce and simmer everything together until the flavors combine.",
        text12: "5. Serve the dish hot, ofter with bread.",
        title4: "Characteristics",
        text13: "• It is a one pot dish whose main ingredients are beans, sausage, bacon and tomato sauce.",
        text14: "• It's a very nutritious and warming dish, which is why it often appears on Polish tables during colder days.",
        text15: "• Despite its name, this dish has nothing to do with Brittany in France. The name probably comes from the term 'à la bretonne' , which in French cuisine means a dish with beans.",
      },
      CakeWithBeans: {
        title: "Bean Pastries",
        description: "This recipe is inspired by the Portuguese 'pastéis de feijão', but adapted to be more like a cake. It's moist, delicious and surprisingly made with white beans!",
        title2: "Ingredients",
        text: "• 1 (15 ounces) can cannellini beans, rinsed and drained very well",
        text2: "• 3 large eggs",
        text3: "• 1/2 cup of granulated sugar",
        text4: "• 1/4 cup unsalted butter, melted and cooled",
        text5: "• 1 teaspoon vanilla extract",
        text6: "• 1/4 tea spoon almond extract",
        text7: "• 1/4 ground almonds",
        text8: "• 1/4 teaspoon salt",
        text9: "• Powdered sugar for dustig (Opticional)",
        title3: "Instructions",
        text10: "1. Preheat the oven at 175ºC (350ºF). Grease and flour a 9-inch round cake pan.",
        text11: "2. In a food processor or blender, combine the beans, eggs, sugar, melted butter, vanilla extract, almond extract, ground almonds, and salt. Process until completly smooth.",
        text12: "3. Pour the batter into the prepared pan and bake for 30-35 minutes, or until a toothpick inserted into the center comes out clean.",
        title4: "Tips",
        text13: "• Make sure to drain and rinse the beans very well to avoid a beany flavour.",
        text14: "• You can replace the cannellini beans with another type of white beans, such as navy beans or Great Northern beans.",
        text15: "• If you don't have ground almonds, you can use almond flour or finely chopped almonds.",
        text16: "• Serve the cake with a dollop of whipped cream or a scoop of ice cream.",
      },
      Borscht: {
        title: "Borscht",
        description: "Borscht with Beans is an interesting variation of traditional Borscht, combining sweet and sour taste of beets with the satisfying addition of beans.",
        title2: "Ingredients (Examples):",
        text: "• Beets",
        text2: "• Carrots",
        text3: "• Parsley Root",
        text4: "• Celery Root",
        text5: "• Onion",
        text6: "• Garlic",
        text7: "• Beans (white, red, or pinto)",
        text8: "• Vegetable broth",
        text9: "• Vinegar or Lemon Juice",
        text10: "• Sugar (Optional)",
        text11: "• Spices (Bay Leaf, allspice, pepper, salt)",
        title3: "Instructions",
        text12: "1. Cook the root vegetables and beets in the borth until tender.",
        text13: "2. Cook the beans seperatly or add them to the soup towards the end of cooking.",
        text14: "3. Blend or grate the beets and some of the vegetables.",
        text15: "4. Add the beans, vinegar or lemon juice, sugar (optional), and spices.",
        text16: "5. Cook for a few more minutes to allow the flavors to combine.",
        text17: "6. Serve with bread, potatoes or other accompaniments.",
        title4: "Characteristics",
        text18: "• Borscht with Beans is a soup that combines the traditional ingredients of borscht (beets, root vegetables) with the adition of beans.",
        text19: "• Beans add thickness, satiety, and nutritional value to the soup.",
        text20: "• It can be served both hot or cold, depending on preference.",
        text21: "• It is a vegetarian or vegan dish depending on the ingredients used (e.g., vegetable broth).",
      },
      SourRyeSoup: {
        title: "Sour Rye Soup",
        description: "Sour Rye Soup is a traditional Polish sour rye soup. It's hearty and distinctive dish with a unique flavor profile.",
        title2: "Ingredients",
        text: "• Polish Sausage",
        text2: "• Smoked Bacon or ham",
        text3: "• Potatoes",
        text4: "• Hard-boiled eggs",
        text5: "• Onions and Garlic",
        text6: "• Marjoram and orther spices",
        title3: "Characteristics",
        text7: "• Sour Base: The defining feature of 'żurek' is its sour, fermented base made from rye flour. This 'zakwas' (sourdoug starter) gives the soup its characteristic tang.",
        text8: "• Variations: There are regional variations of 'żurek'. Some variations may inclue mushrooms, horseradish, or other additions.",
        text9: "• Traditional Significance: Żurek is often associated with Easter in Poland, where it's a popular dish served during the holiday. It is also a common comfort food enjoyed throughout the year.",
        title4: "How it's Served",
        text10: "• Żurek is often served in a bowl or, for a more traditional presentation, in a hollowed-out loaf of bread.",
        text11: "• It's typically garnished with hard-boiled egg halves and fresh herbs.",
      },
      Pierogi: {
        title: "Pierogi",
        description: "Pierogi are a beloved and iconic Polish dumpling. They're a staple of Polish cuisine and are enjoyed in many variations. Here's a breakdown of what makes pierogi so special:",
        title2: "Characteristics",
        text: "• Dough: The dough is traditionally made from flour, water, eggs (sometimes), and a bit of salt. It's rolled out thinly and cut out into circles or squares.",
        text2: "Fillings:",
        text3: "• Potato and Cheese (Pierogi Ruskie): A classic combination of mashed potatoes and farmer's cheese or white cheese.",
        text4: "• Meat (Pierogi z Mięsem): Filled with ground meat, often pork or beef, seasoned with onions and spices.",
        text5: "• Cabbage and Mushroom (Pierogi z Kapustą i Grzybami): A vegetarian option with a flavorful filling of sauerkraut and mushrooms.",
        title3: "Instructions",
        text6: "Pierogi are typically boiled until they float, and then they can be pan-fried or baked for added flavor and texture",
        title4: "Pierogi is often served with:",
        text7: "• Sour cream.",
        text8: "• Fried onions.",
        text9: "• Bacon bits.",
        text10: "• Sometimes with sugar or fruit sauces for sweet varieties.",
      },
      BeanPastries: {
        title: "Bean Pastries",
        description: "Bean pastries, or 'pastéis de feijão', are a traditional Portuguese delicacy, known for their sweet flavor and unique texture. Here's a summary of what makes them so special:  ",
        title2: "Ingredients and Preparation:",
        text: "• The main ingredients include cooked white beans, sugar, eggs, and ground almonds.",
        text2: "• Preparation involves creating a creamy filling from the bean puree, which is then placed in a thin, crispy pastry.",
        text3: "• The result is a pastry with a contrasting texture between the crispy pastry and the smooth filling.",
        title3: "Characteristics:",
        text4: "• Bean pastries are distinguished by their sweet, but not overly cloying, flavor and their creamy texture.",
        text5: "• They are generally small, making them ideal for enjoying as an individual sweet.",
        text6: "• They are often sprinkled with powdered sugar, which gives them an even more appetizing appearance.",
        title4: "Popularity and Consumption:",
        text7: "• Bean pastries are very popular in Portugal, found in pastry shops and cafes throughout the country.",
        text8: "• They are a popular choice to accompany coffee or as a dessert after a meal.",
        text9: "• Their popularity also extends to other countries, where Portuguese confectionery is appreciated.",
      },
      FolkCostumes: {
        title: "Folk Costumes",
        title2: "Polish Folk Costumes",
        text: "Polish folk costumes are rich and diverse, reflecting the folk of individual regions. Here is some general information:",
        title3: "Diversity:",
        text2: "• Each region of Poland has its own unique costumes, differing in colors, patterns, and elements.",
        text3: "• The most well-known include costumes from: Krákow, Łowicz, and the mountains (Góralski)",
        title4: "Costume Elements:",
        text4: "• Women: skirts, blouses, corsets, shawls, necklaces.",
        text5: "• Man: trousers, shirts, vests, belts, hats.",
        title5: "Ocasions:",
        text6: "• Folk Costumes are worn during holidays, festivals, and regional celebrations.",
        text7: "• They are also used by folk groups.",
        title6: "Symbolism:",
        text8: "• Folk Costumes are an important element of Polish culture and symbolism.",
        text9: "• They reflect local history and customs.",
      },
      FatThursday: {
        title: "Fat Thursday",
        text: "Fat Thursday, known locally as Tłusty Czwartek, is a day linked to the church calendar. On this day, for many Polish people, it is the last day to eat lots of fatty, sugary food and drink alcohol before Lent (the Christian festival). Some Polish people abstain from alcohol and meat completely during Lent. Others continue to eat meat and alcohol during this six-week period, but almost every Polish person celebrates Fat Thursday as the final day of eating indulgent foods ahead of Easter.",
        title2: "Who celebrates Fat Thursday?",
        text2: "Fat Thursday is celebrated nationwide in Poland and also by Polish people living abroad. Even immigrants and tourists who live in Poland love to celebrate this exciting day. The day has more recently become popular with foreign travel bloggers in Poland, including Chido Fajny and Northern Irishman in Poland, both of whom have written about the day. It is a day of fun, where foreigners can really see a Polish tradition in action.",
        title3: "What food is mostly consumed on Fat Thursday?",
        text3: "In general, all types of sweet and fatty foods are devoured all over Poland on Fat Thursday, but the two most popular are Pączki and Faworki.",
      },
      WetMonday: {
        title: "Wet Monday",
        text: "Śmigus-Dyngus? Sounds peculiar, so let us explain. Śmigus-Dyngus, also known as lany poniedziałek (Wet Monday), is a Polish Easter Monday tradition which, in short, involves people throwing copious amounts of water at each other.",
        text2: "As it turns out, Śmigus and Dyngus were originally two separate customs. There are many different ideas, however, of what they looked like and exactly where they came from. Most commonly, Śmigus was known to involve the symbolic whacking of people’s legs with palm fronds or willows and drenching them in cold water. This was meant to cleanse them of dirt and diseases, and later of sin.",
      },
      SecondWedding: {
        title: "Second Wedding",
        text: "Some weddings last two days, the second day is called 'poprawiny', so you can basically squeeze out every last bit of energy from people and stuff them with more food. Poprawiny usually ends a bit earlier, but it's still a food, drink and dance affair, a little less formal.",
        text2: " Many Polish wedding receptions still open with the traditional presentation of bread and salt. Upon the newly-weds’ arrival at the reception, their parents present them with these two essentials. The bread is specially prepared and often decorated with the names of the couple. This gift of bread and salt is symbolic – bread is offered so that the couple may never know hunger, while salt reminds them of life’s difficulties and the importance of learning to cope.",
      },
      discoverTitle: "Discover More About Our Region",
      discoverText: "Explore local attractions, food, culture, and community living in our town.",
    },

    pl: {
      welcome: plBanner,
      home: "Strona główna",
      locations: "Lokalizacje",
      gastronomy: "Gastronomia",
      traditions: "Tradycje",
      elderlyHomes: "Domy spokojnej starości",
      aboutUs: "O nas",
      menuItems: {
        zakliczyn: "Zakliczyn",
        melsztyn: "Melsztyn",
        musicCenter: "Centrum Muzyczne",
        eurovelo: "Eurovelo Motesk",
        stIdzi: "Św. Idzi",
      },
      zakliczyn: {
        title: "Zakliczyn",
        description: "Zakliczyn to malownicze małe miasteczko położone w południowej części Polski, znane ze swojego historycznego znaczenia i urody krajobrazu. Oto kilka kluczowych informacji:",
        title2: "Lokalizacja:",
        text: "• Zakliczyn znajduje się w województwie małopolskim, około 80 kilometrów na południowy wschód od Krakowa.",
        text2: "• Leży nad brzegiem rzeki Dunajec, w regionie charakteryzującym się pagórkowatym terenem i naturalnym krajobrazem.",
        title3: "Historia:",
        text3: "• Historia Zakliczyna sięga XIV wieku, a pierwsze wzmianki pojawiają się w 1326 roku.",
        text4: "• Miasto uzyskało prawa miejskie w 1558 roku, co przyczyniło się do jego rozwoju gospodarczego i kulturalnego.",
      },
      melsztyn: {
        title: "Melsztyn",
        description: "Historyczna wieś z ruinami zamku. Melsztyn to urokliwa wieś w regionie Małopolski, znana głównie z ruin średniowiecznego zamku. Oto przegląd:",
        title2: "Lokalizacja:",
        text: "• Melsztyn znajduje się w województwie małopolskim, w południowej Polsce.",
        text2: "• Leży na lewym brzegu rzeki Dunajec.",
        text3: "• Znajduje się około 5 kilometrów na północny zachód od Zakliczyna, 25 kilometrów na południowy zachód od Tarnowa i 64 kilometry na wschód od Krakowa.",
        title3: "Zamek Melsztyn:",
        text4: "• Główną atrakcją Melsztyna są ruiny zamku Melsztyn.",
        text5: "• Ten średniowieczny zamek ma bogatą historię sięgającą XIV wieku.",
        text6: "• Zamek był rezydencją Jana z Melsztyna.",
        text7: "• Ruiny oferują panoramiczne widoki na okoliczny krajobraz i są popularnym miejscem wśród turystów i miłośników historii.",
        text8: "• Ruiny zamku składają się z głównej wieży oraz otaczających ją murów.",
        title4: "Historia:",
        text9: "• Wieś ma długą historię, ściśle związaną z zamkiem.",
        text10: "• Zamek odegrał istotną rolę w historii regionu.",
      },
      MusicCenter: {
        title: "Centrum Muzyczne",
        description: "Europejskie Centrum Muzyki Krzysztofa Pendereckiego to wyjątkowa instytucja kulturalna położona w Lusławicach, w województwie małopolskim. Oto kilka kluczowych informacji:",
        title2: "Misja i działalność:",
        text: "• Centrum ma na celu rozwój talentów muzycznych młodych, uzdolnionych instrumentalistów, wokalistów i dyrygentów z całego świata.",
        text2: "• Realizuje to poprzez kursy mistrzowskie, warsztaty, koncerty i inne wydarzenia artystyczne i edukacyjne.",
        title3: "Lokalizacja:",
        text3: "• Centrum znajduje się w Lusławicach, niedaleko miejsca, gdzie Krzysztof Penderecki osiedlił się w 1976 roku.",
        text4: "• Lusławice położone są w pobliżu Zakliczyna.",
        title4: "Architektura i infrastruktura:",
        text5: "• Serce centrum stanowi sala koncertowa mogąca pomieścić 650 słuchaczy.",
        text6: "• Scena o powierzchni 200 metrów kwadratowych jest zaprojektowana do wszechstronnego użytku.",
        text7: "• Dzięki ruchomej fosie orkiestrowej możliwe jest wystawianie oper i baletów.",
        text8: "• Obok centrum znajduje się piękne arboretum, będące dziełem Elżbiety i Krzysztofa Pendereckich.",
        title5: "Znaczenie:",
        text9: "• Centrum jest ważnym ośrodkiem muzycznym w Polsce, promującym i wspierającym młode talenty.",
        text10: "• To także miejsce upamiętniające dorobek jednego z najwybitniejszych polskich kompozytorów.",
      },
      EuroveloMotesk: {
        title: "Eurovelo Mostek",
        title2: "Trasy EuroVelo:",
        text: "• EuroVelo to sieć dalekodystansowych tras rowerowych, które przecinają Europę. Trasy te mają na celu promowanie turystyki rowerowej i zapewnienie infrastruktury dla rowerzystów.",
        text2: "• Trasy te pozwalają odkrywać różnorodne krajobrazy Europy.",
        title3: "Połączenie z Mostkiem i Zakliczynem:",
        text3: "• Region Małopolski, w którym znajdują się Mostek i Zakliczyn, staje się coraz bardziej popularny wśród turystów rowerowych.",
        text4: "• Rzeka Dunajec, przepływająca przez ten obszar, jest kluczowym elementem przyciągającym rowerzystów. Rzeki często oferują stosunkowo płaskie trasy, co czyni je idealnymi do jazdy na rowerze.",
        text5: "• Bardzo możliwe, że trasy EuroVelo przebiegają przez ten region, ponieważ wykorzystują one istniejącą infrastrukturę i elementy naturalne.",
        text6: "• Aby uzyskać dokładne informacje o tym, która trasa EuroVelo przebiega przez te miejsca, zalecam odwiedzenie oficjalnej strony EuroVelo.",
      },
      StIdzi: {
        title: "Święty Idzi",
        description: "Kościół św. Idziego w Zakliczynie to ważny historyczny i religijny zabytek. Oto informacje na jego temat:",
        title2: "Znaczenie historyczne:",
        text: "• To rzymskokatolicki kościół parafialny położony w Zakliczynie, w województwie małopolskim.",
        text2: "• Historia kościoła sięga okresu średniowiecza.",
        text3: "• Zawiera elementy architektoniczne z różnych epok, odzwierciedlające rozwój historyczny miasta.",
        title3: "Znaczenie religijne:",
        text4: "• Pełni funkcję kościoła parafialnego dla lokalnej wspólnoty katolickiej.",
        text5: "• Jest poświęcony św. Idziemu, popularnemu świętemu średniowiecznemu.",
        title4: "Cechy architektoniczne:",
        text6: "• Kościół prezentuje mieszankę stylów gotyckiego, renesansowego i barokowego.",
        text7: "• Posiada charakterystyczną wieżę.",
        text8: "• Wnętrze zawiera historyczne dzieła sztuki sakralnej i artefakty.",
        title5: "Lokalizacja:",
        text9: "• Znajduje się w mieście Zakliczyn, które samo w sobie ma bogatą historię.",
      },
      RetirementHomes: {
        title: "Domy spokojnej starości",
        text1: "W Polsce domy spokojnej starości, znane również jako domy opieki lub domy seniorów, odgrywają kluczową rolę w opiece nad osobami starszymi. Oto kilka kluczowych aspektów dotyczących tych placówek:",
        title2: "Domy opieki publicznej:",
        text3: "• Zarządzane przez władze lokalne.",
        text4: "• Koszty pobytu pokrywane są częściowo ze środków państwa.",
        text5: "• Często mają długie listy oczekujących.",
        title3: "• Oferowane usługi:",
        text7: "• Opieka 24-godzinna: Pomoc w codziennych czynnościach, takich jak jedzenie, ubieranie się i higiena osobista.",
        text8: "• Opieka medyczna: monitorowanie stanu zdrowia, podawanie leków i rehabilitacja.",
        text9: "• Odżywianie: Zbilansowane posiłki dostosowane do potrzeb seniorów.",
        text10: "• Zajęcia rekreacyjno-terapeutyczne: organizowane w celu aktywizacji seniorów i poprawy ich samopoczucia.",
        text11: "• Opieka psychologiczna: wsparcie emocjonalne dla mieszkańców.",
      },
      BakedBeans: {
        title: "Pieczona fasola",
        description: "Fasolka po bretońsku to popularne i sycące danie kuchni polskiej, znane z bogatego smaku i prostoty przygotowania!",
        title2: "Składniki",
        text: "• Fasola (najczęściej biała)",
        text2: "• Kiełbasa (najlepiej wędzona)",
        text3: "• Wędzony boczek",
        text4: "• Cebula",
        text5: "• Czosnek",
        text6: "• Przecier pomidorowy lub pomidory w puszce",
        text7: "• Przyprawy: majeranek, liść laurowy, ziele angielskie, pieprz, sól",
        title3: "Instrukcje",
        text8: "1. Fasolę namoczyć na kilka godzin, a następnie gotować, aż będzie miękka.",
        text9: "2. Na patelni podsmaż posiekaną cebulę, boczek i kiełbasę.",
        text10: "3. Dodaj czosnek i przyprawy, następnie przecier pomidorowy lub pomidory z puszki.",
        text11: "4. Dodaj ugotowaną fasolę do sosu i gotuj wszystko razem, aż smaki się połączą.",
        text12: "5. Serve the dish hot, ofter with bread.",
        title4: "Charakterystyka",
        text13: "• Jest to danie jednogarnkowe, którego głównymi składnikami są fasola, kiełbasa, boczek i sos pomidorowy.",
        text14: "• Jest to danie bardzo pożywne i rozgrzewające, dlatego też często pojawia się na polskich stołach w chłodniejsze dni.",
        text15: "• Pomimo nazwy, danie to nie ma nic wspólnego z Bretanią we Francji. Nazwa prawdopodobnie pochodzi od terminu „à la bretonne”, który w kuchni francuskiej oznacza potrawę z fasolą.",
      },
      CakeWithBeans: {
        title: "Ciastka Fasolowe",
        description: "Ten przepis jest inspirowany portugalskimi 'pastéis de feijão', ale dostosowany do bardziej przypominającego ciasto. Jest wilgotny, pyszny i zaskakująco zrobiony z białej fasoli!",
        title2: "Składniki",
        text: "• 1 (15 uncji) puszka fasoli cannellini, dokładnie wypłukanej i odsączonej",
        text2: "• 3 duże jajka",
        text3: "• 1/2 szklanki cukru granulowanego",
        text4: "• 1/4 szklanki niesolonego masła, roztopionego i ostudzonego",
        text5: "• 1 łyżeczka ekstraktu waniliowego",
        text6: "• 1/4 łyżeczki ekstraktu migdałowego",
        text7: "• 1/4 zmielonych migdałów",
        text8: "• 1/4 łyżeczki soli",
        text9: "• Cukier puder do posypania (opcjonalnie)",
        title3: "Instrukcje",
        text10: "1. Rozgrzej piekarnik do 175ºC (350ºF). Nasmaruj tłuszczem i oprósz mąką okrągłą formę do ciasta o średnicy 9 cali.",
        text11: "2. W robocie kuchennym lub blenderze wymieszaj fasolę, jajka, cukier, roztopione masło, ekstrakt waniliowy, ekstrakt migdałowy, zmielone migdały i sól. Miksuj do uzyskania całkowicie gładkiej masy.",
        text12: "3. Wlej ciasto do przygotowanej formy i piecz przez 30–35 minut, lub do momentu, aż wykałaczka włożona w środek ciasta będzie czysta.",
        title4: "Porady",
        text13: "• Aby uniknąć fasolowego posmaku, należy ją bardzo dokładnie odsączyć i opłukać.",
        text14: "• Fasolę cannellini możesz zastąpić innym rodzajem białej fasoli, np. fasolą amerykańską lub fasolą białą odmiany Great Northern.",
        text15: "• Jeśli nie masz zmielonych migdałów, możesz użyć mąki migdałowej lub drobno posiekanych migdałów.",
        text16: "• Podawaj ciasto z kleksem bitej śmietany lub gałką lodów.",
      },
      Borscht: {
        title: "Barszcz",
        description: "Barszcz z fasolą to ciekawa odmiana tradycyjnego barszczu, łącząca słodko-kwaśny smak buraków z sycącym dodatkiem fasoli.",
        title2: "Składniki (przykładowe):",
        text: "• Buraki",
        text2: "• Marchew",
        text3: "• Korzeń pietruszki",
        text4: "• Korzeń selera",
        text5: "• Cebula",
        text6: "• Czosnek",
        text7: "• Fasola (biała, czerwona lub pinto)",
        text8: "• Bulion warzywny",
        text9: "• Ocet lub sok z cytryny",
        text10: "• Cukier (opcjonalnie)",
        text11: "• Przyprawy (liść laurowy, ziele angielskie, pieprz, sól)",
        title3: "Instrukcje",
        text12: "1. Gotuj warzywa korzeniowe i buraki w bulionie, aż będą miękkie.",
        text13: "2. Ugotuj fasolę osobno lub dodaj ją do zupy pod koniec gotowania.",
        text14: "3. Zblenduj lub zetrzyj buraki i część warzyw.",
        text15: "4. Dodaj fasolę, ocet lub sok z cytryny, cukier (opcjonalnie) i przyprawy.",
        text16: "5. Gotuj jeszcze kilka minut, aby smaki się połączyły.",
        text17: "6. Podawaj z chlebem, ziemniakami lub innymi dodatkami.",
        title4: "Charakterystyka",
        text18: "• Barszcz z fasolą to zupa łącząca tradycyjne składniki barszczu (buraki, warzywa korzeniowe) z dodatkiem fasoli.",
        text19: "• Fasola dodaje gęstości, sytości i wartości odżywczych zupie.",
        text20: "• Może być podawana na gorąco lub na zimno, w zależności od preferencji.",
        text21: "• Jest to danie wegetariańskie lub wegańskie, w zależności od użytych składników (np. bulion warzywny)."
      },
      SourRyeSoup: {
        title: "Żurek",
        description: "Żurek to tradycyjna polska zupa na zakwasie żytnim. To sycące i charakterystyczne danie o unikalnym profilu smakowym.",
        title2: "Składniki",
        text: "• Polska kiełbasa",
        text2: "• Wędzony boczek lub szynka",
        text3: "• Ziemniaki",
        text4: "• Jajka na twardo",
        text5: "• Cebula i czosnek",
        text6: "• Majeranek i inne przyprawy",
        title3: "Charakterystyka",
        text7: "• Kwaśna baza: Główną cechą żurku jest jego kwaśna, fermentowana baza z mąki żytniej. Ten zakwas nadaje zupie charakterystyczną kwasowość.",
        text8: "• Odmiany: Istnieją regionalne odmiany żurku. Niektóre z nich mogą zawierać grzyby, chrzan lub inne dodatki.",
        text9: "• Znaczenie tradycyjne: Żurek często kojarzony jest z Wielkanocą w Polsce, kiedy to jest popularnym daniem podawanym podczas świąt. Jest również popularnym daniem na co dzień przez cały rok.",
        title4: "Sposób podania",
        text10: "• Żurek często podaje się w misce lub, bardziej tradycyjnie, w wydrążonym bochenku chleba.",
        text11: "• Zazwyczaj jest ozdobiony połówkami jajek na twardo i świeżymi ziołami."
      },
      Pierogi: {
        title: "Pierogi",
        description: "Pierogi to ukochane i kultowe polskie pierożki. Są podstawą kuchni polskiej i występują w wielu odmianach. Oto, co sprawia, że pierogi są tak wyjątkowe:",
        title2: "Charakterystyka",
        text: "• Ciasto: Tradycyjnie ciasto przygotowuje się z mąki, wody, jajek (czasami) i odrobiny soli. Rozwałkowuje się je cienko i wykrawa kółka lub kwadraty.",
        text2: "Nadzienia:",
        text3: "• Ziemniaki i ser (Pierogi Ruskie): Klasyczne połączenie ziemniaków i twarogu lub białego sera.",
        text4: "• Mięso (Pierogi z Mięsem): Nadzienie z mielonego mięsa, często wieprzowego lub wołowego, przyprawione cebulą i przyprawami.",
        text5: "• Kapusta i grzyby (Pierogi z Kapustą i Grzybami): Wersja wegetariańska z aromatycznym farszem z kiszonej kapusty i grzybów.",
        title3: "Instrukcje",
        text6: "Pierogi zazwyczaj gotuje się do momentu, aż wypłyną na powierzchnię, a następnie można je podsmażyć lub zapiec dla lepszego smaku i tekstury.",
        title4: "Pierogi często podaje się z:",
        text7: "• Śmietaną.",
        text8: "• Smażoną cebulką.",
        text9: "• Skwarkami.",
        text10: "• Czasem z cukrem lub sosami owocowymi w przypadku wersji na słodko."
      },
      BeanPastries: {
        title: "Ciastka z Fasoli",
        description: "Ciastka z fasoli, czyli 'pastéis de feijão', to tradycyjny portugalski przysmak, znany ze swojego słodkiego smaku i unikalnej konsystencji. Oto podsumowanie tego, co czyni je tak wyjątkowymi:",
        title2: "Składniki i przygotowanie:",
        text: "• Główne składniki to gotowana biała fasola, cukier, jajka i mielone migdały.",
        text2: "• Przygotowanie polega na stworzeniu kremowego nadzienia z purée z fasoli, które następnie umieszcza się w cienkim, chrupiącym cieście.",
        text3: "• Efektem jest ciastko o kontrastującej konsystencji — między chrupiącym ciastem a gładkim nadzieniem.",
        title3: "Charakterystyka:",
        text4: "• Ciastka z fasoli wyróżniają się słodkim, ale nie przesadnie mdlącym smakiem oraz kremową konsystencją.",
        text5: "• Są zazwyczaj niewielkie, co czyni je idealnymi jako pojedynczy deser.",
        text6: "• Często są posypywane cukrem pudrem, co nadaje im jeszcze bardziej apetyczny wygląd.",
        title4: "Popularność i spożycie:",
        text7: "• Ciastka z fasoli cieszą się dużą popularnością w Portugalii i można je znaleźć w cukierniach i kawiarniach w całym kraju.",
        text8: "• Są popularnym dodatkiem do kawy lub deserem po posiłku.",
        text9: "• Ich popularność rozciąga się także na inne kraje, gdzie docenia się portugalskie wyroby cukiernicze.",
      },
      FolkCostumes: {
        title: "Stroje Ludowe",
        title2: "Polskie Stroje Ludowe",
        text: "Polskie stroje ludowe są bogate i zróżnicowane, odzwierciedlając kulturę poszczególnych regionów. Oto kilka ogólnych informacji:",
        title3: "Różnorodność:",
        text2: "• Każdy region Polski ma swoje unikalne stroje, różniące się kolorami, wzorami i elementami.",
        text3: "• Najbardziej znane to stroje z: Krakowa, Łowicza i gór (Góralskie).",
        title4: "Elementy Stroju:",
        text4: "• Kobiety: spódnice, bluzki, gorsety, chusty, naszyjniki.",
        text5: "• Mężczyźni: spodnie, koszule, kamizelki, pasy, kapelusze.",
        title5: "Okazje:",
        text6: "• Stroje ludowe noszone są podczas świąt, festiwali i uroczystości regionalnych.",
        text7: "• Używane są również przez zespoły ludowe.",
        title6: "Symbolika:",
        text8: "• Stroje ludowe są ważnym elementem polskiej kultury i symboliki.",
        text9: "• Odzwierciedlają lokalną historię i zwyczaje."
      },
      FatThursday: {
        title: "Tłusty Czwartek",
        text: "Tłusty Czwartek to dzień związany z kalendarzem kościelnym. Dla wielu Polaków jest to ostatni dzień, kiedy można objadać się tłustymi, słodkimi potrawami i pić alkohol przed Wielkim Postem (chrześcijańskim okresem pokuty). Niektórzy Polacy całkowicie rezygnują z alkoholu i mięsa podczas postu. Inni nadal jedzą mięso i piją alkohol w tym sześciotygodniowym okresie, ale niemal każdy Polak świętuje Tłusty Czwartek jako ostatni dzień obfitego jedzenia przed Wielkanocą.",
        title2: "Kto świętuje Tłusty Czwartek?",
        text2: "Tłusty Czwartek obchodzony jest w całej Polsce oraz przez Polaków mieszkających za granicą. Nawet imigranci i turyści mieszkający w Polsce chętnie celebrują ten wyjątkowy dzień. W ostatnich latach dzień ten zyskał popularność także wśród zagranicznych blogerów podróżniczych w Polsce, w tym Chido Fajny i Northern Irishman in Poland, którzy pisali o tym święcie. To dzień zabawy, w którym obcokrajowcy mogą zobaczyć polską tradycję w praktyce.",
        title3: "Jakie jedzenie jest najczęściej spożywane w Tłusty Czwartek?",
        text3: "Ogólnie rzecz biorąc, w Tłusty Czwartek w całej Polsce zjada się wszelkiego rodzaju słodkie i tłuste potrawy, ale dwie najpopularniejsze to pączki i faworki."
      },
      WetMonday: {
        title: "Lany Poniedziałek",
        text: "Śmigus-Dyngus? Brzmi osobliwie, więc pozwól, że wyjaśnimy. Śmigus-Dyngus, znany również jako lany poniedziałek, to polska tradycja obchodzona w wielkanocny poniedziałek, która w skrócie polega na oblewaniu się nawzajem dużymi ilościami wody.",
        text2: "Okazuje się, że Śmigus i Dyngus były pierwotnie dwoma odrębnymi zwyczajami. Istnieje wiele różnych teorii na temat tego, jak wyglądały i skąd dokładnie pochodzą. Najczęściej uważa się, że Śmigus polegał na symbolicznym smaganiu nóg gałązkami palmowymi lub wierzbowymi oraz polewaniu zimną wodą. Miało to oczyszczać z brudu i chorób, a później również z grzechu."
      },
      AboutUs: {
        title: "About Us",
      },
      discoverTitle: "Odkryj więcej o naszym regionie",
      discoverText: "Poznaj lokalne atrakcje, jedzenie, kulturę i życie społeczności w naszym mieście.",
    }
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, translations }
    }>
      {children}
    </LanguageContext.Provider >
  );
};

export const useLanguage = () => useContext(LanguageContext);