import React, { createContext, useState, useContext } from 'react';
import ukBanner from '../assets/uk_banner.png'
import plBanner from '../assets/pl_banner.png'

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');
  const translations = {
    en: {
      welcome: ukBanner,
      home: "Home",
      locations: "Locations",
      gastronomy: "Gastronomy",
      traditions: "Traditions",
      elderlyHomes: "Retirement Homes",
      menuItems: {
        zakliczyn: "Zakliczyn",
        melsztyn: "Melsztyn",
        musicCenter: "Music Center",
        eurovelo: "Eurovelo Motesk",
        stIdzi: "St. Idzi",
      },
      zakliczyn: {
        title: "Zakliczyn",
        description: ""
      },
      melsztyn: {
        title: "Melsztyn",
        description: ""
      },
      MusicCenter: {
        title: "Music Center",
        description: ""
      },
      EuroveloMostek: {
        title: "Eurovelo Motesk",
        description: ""
      },
      StIdziZakliczyn: {
        title: "St. Idzi",
        description: "",
      },
      RetirementHomes: {
        title: "Retirement Homes",
        text1: "In Poland, retirement homes, also known as care homes or senior homes, play a crucial role in caring for the elderly. Here are some key aspects regarding these facilities:",
        title2: "Public Care Homes:",
        text3: "• Run by local governments.",
        text4: "• The costs of stay are partially funded by the state.",
        text5: "• Often have long wait lists.",
        title3: "Services Offered:",
        text7: "• 24-Hour Care: Assistance with daily activities, such as eating, dressing, and personal hygiene.",
        text8: "• Medical Care: Monitoring health conditions, administering medications, and rehabilitation.",
        text9: "• Nutrion: Balanced meals tailored to the needs of seniors.",
        text10: "• Recreation and Therapeutic Activities: Organized to activate seniors and improve their well-being.",
        text11: "• Psychological Care: Emotional support for residents.",
      },
      BakedBeans: {
        title: "Baked Beans",
        description: "Baked Beans is a popular and hearty dish from Polish cuisine, known for its rich flavor and simple preparation!",
        title2: "Ingredients",
        text: "• Beans (most often white)",
        text2: "• Sausage (preferably smoked)",
        text3: "• Smoked bacon",
        text4: "• Onion",
        text5: "• Garlic",
        text6: "• Tomato puree or canned tomatoes",
        text7: "• Spices: Marjoram, bay leaf, allspice, pepper, salt",
        title3: "Instructions",
        text8: "1. Soak the beans for several hours, then cook until soft.",
        text9: "2. Sauté the chopped onion, bacon and sausage in a pan.</div>",
        text10: "3. Add the garlic and spices, then the tomato puree or canned tomatoes.",
        text11: "4. Add the coocked beans to the sauce and simmer everything together until the flavors combine.",
        text12: "5. Serve the dish hot, ofter with bread.",
        title4: "Characteristics",
        text13: "• It is a one pot dish whose main ingredients are beans, sausage, bacon and tomato sauce.",
        text14: "• It's a very nutritious and warming dish, which is why it often appears on Polish tables during colder days.",
        text15: "• Despite its name, this dish has nothing to do with Brittany in France. The name probably comes from the term 'à la bretonne' , which in French cuisine means a dish with beans.",
      },
      CakeWithBeans: {
        title: "Bean Pastries",
        description: "This recipe is inspired by the Portuguese 'pastéis de feijão', but adapted to be more like a cake. It's moist, delicious and surprisingly made with white beans!",
        title2: "Ingredients",
        text: "• 1 (15 ounces) can cannellini beans, rinsed and drained very well",
        text2: "• 3 large eggs",
        text3: "• 1/2 cup of granulated sugar",
        text4: "• 1/4 cup unsalted butter, melted and cooled",
        text5: "• 1 teaspoon vanilla extract",
        text6: "• 1/4 tea spoon almond extract",
        text7: "• 1/4 ground almonds",
        text8: "• 1/4 teaspoon salt",
        text9: "• Powdered sugar for dustig (Opticional)",
        title3: "Instructions",
        text10: "1. Preheat the oven at 175ºC (350ºF). Grease and flour a 9-inch round cake pan.",
        text11: "2. In a food processor or blender, combine the beans, eggs, sugar, melted butter, vanilla extract, almond extract, ground almonds, and salt. Process until completly smooth.",
        text12: "3. Pour the batter into the prepared pan and bake for 30-35 minutes, or until a toothpick inserted into the center comes out clean.",
        title4: "Tips",
        text13: "• Make sure to drain and rinse the beans very well to avoid a beany flavour.",
        text14: "• You can replace the cannellini beans with another type of white beans, such as navy beans or Great Northern beans.",
        text15: "• If you don't have ground almonds, you can use almond flour or finely chopped almonds.",
        text16: "• Serve the cake with a dollop of whipped cream or a scoop of ice cream.",
      },
      Borscht: {
        title: "Borscht",
        description: "Borscht with Beans is an interesting variation of traditional Borscht, combining sweet and sour taste of beets with the satisfying addition of beans.",
        title2: "Ingredients (Examples):",
        text: "• Beets",
        text2: "• Carrots",
        text3: "• Parsley Root",
        text4: "• Celery Root",
        text5: "• Onion",
        text6: "• Garlic",
        text7: "• Beans (white, red, or pinto)",
        text8: "• Vegetable broth",
        text9: "• Vinegar or Lemon Juice",
        text10: "• Sugar (Optional)",
        text11: "• Spices (Bay Leaf, allspice, pepper, salt)",
        title3: "Instructions",
        text12: "1. Cook the root vegetables and beets in the borth until tender.",
        text13: "2. Cook the beans seperatly or add them to the soup towards the end of cooking.",
        text14: "3. Blend or grate the beets and some of the vegetables.",
        text15: "4. Add the beans, vinegar or lemon juice, sugar (optional), and spices.",
        text16: "5. Cook for a few more minutes to allow the flavors to combine.",
        text17: "6. Serve with bread, potatoes or other accompaniments.",
        title4: "Characteristics",
        text18: "• Borscht with Beans is a soup that combines the traditional ingredients of borscht (beets, root vegetables) with the adition of beans.",
        text19: "• Beans add thickness, satiety, and nutritional value to the soup.",
        text20: "• It can be served both hot or cold, depending on preference.",
        text21: "• It is a vegetarian or vegan dish depending on the ingredients used (e.g., vegetable broth).",
      },
      SourRyeSoup: {
        title: "Sour Rye Soup",
        description: "Sour Rye Soup is a traditional Polish sour rye soup. It's hearty and distinctive dish with a unique flavor profile.",
        title2: "Ingredients",
        text: "• Polish Sausage",
        text2: "• Smoked Bacon or ham",
        text3: "• Potatoes",
        text4: "• Hard-boiled eggs",
        text5: "• Onions and Garlic",
        text6: "• Marjoram and orther spices",
        title3: "Characteristics",
        text7: "• Sour Base: The defining feature of 'żurek' is its sour, fermented base made from rye flour. This 'zakwas' (sourdoug starter) gives the soup its characteristic tang.",
        text8: "• Variations: There are regional variations of 'żurek'. Some variations may inclue mushrooms, horseradish, or other additions.",
        text9: "• Traditional Significance: Żurek is often associated with Easter in Poland, where it's a popular dish served during the holiday. It is also a common comfort food enjoyed throughout the year.",
        title4: "How it's Served",
        text10: "• Żurek is often served in a bowl or, for a more traditional presentation, in a hollowed-out loaf of bread.",
        text11: "• It's typically garnished with hard-boiled egg halves and fresh herbs.",
      },

      discoverTitle: "Discover More About Our Region",
      discoverText: "Explore local attractions, food, culture, and community living in our town.",
    },

    pl: {
      welcome: plBanner,
      home: "Strona główna",
      locations: "Lokalizacje",
      gastronomy: "Gastronomia",
      traditions: "Tradycje",
      elderlyHomes: "Domy spokojnej starości",
      menuItems: {
        zakliczyn: "Zakliczyn",
        melsztyn: "Melsztyn",
        musicCenter: "Centrum Muzyczne",
        eurovelo: "Eurovelo Motesk",
        stIdzi: "Św. Idzi",
      },
      zakliczyn: {
        title: "Zakliczyn",
        description: ""
      },
      melsztyn: {
        title: "Melsztyn",
        description: ""
      },
      MusicCenter: {
        title: "Centrum Muzyczne",
        description: ""
      },
      EuroveloMostek: {
        title: "Eurovelo Motesk",
        description: ""
      },
      StIdziZakliczyn: {
        title: "Św. Idzi",
        description: ""
      },
      RetirementHomes: {
        title: "Domy spokojnej starości",
        text1: "W Polsce domy spokojnej starości, znane również jako domy opieki lub domy seniorów, odgrywają kluczową rolę w opiece nad osobami starszymi. Oto kilka kluczowych aspektów dotyczących tych placówek:",
        title2: "Domy opieki publicznej:",
        text3: "• Zarządzane przez władze lokalne.",
        text4: "• Koszty pobytu pokrywane są częściowo ze środków państwa.",
        text5: "• Często mają długie listy oczekujących.",
        title3: "• Oferowane usługi:",
        text7: "• Opieka 24-godzinna: Pomoc w codziennych czynnościach, takich jak jedzenie, ubieranie się i higiena osobista.",
        text8: "• Opieka medyczna: monitorowanie stanu zdrowia, podawanie leków i rehabilitacja.",
        text9: "• Odżywianie: Zbilansowane posiłki dostosowane do potrzeb seniorów.",
        text10: "• Zajęcia rekreacyjno-terapeutyczne: organizowane w celu aktywizacji seniorów i poprawy ich samopoczucia.",
        text11: "• Opieka psychologiczna: wsparcie emocjonalne dla mieszkańców.",
      },
      BakedBeans: {
        title: "Pieczona fasola",
        description: "Fasolka po bretońsku to popularne i sycące danie kuchni polskiej, znane z bogatego smaku i prostoty przygotowania!",
        title2: "Składniki",
        text: "• Fasola (najczęściej biała)",
        text2: "• Kiełbasa (najlepiej wędzona)",
        text3: "• Wędzony boczek",
        text4: "• Cebula",
        text5: "• Czosnek",
        text6: "• Przecier pomidorowy lub pomidory w puszce",
        text7: "• Przyprawy: majeranek, liść laurowy, ziele angielskie, pieprz, sól",
        title3: "Instrukcje",
        text8: "1. Fasolę namoczyć na kilka godzin, a następnie gotować, aż będzie miękka.",
        text9: "2. Na patelni podsmaż posiekaną cebulę, boczek i kiełbasę.",
        text10: "3. Dodaj czosnek i przyprawy, następnie przecier pomidorowy lub pomidory z puszki.",
        text11: "4. Dodaj ugotowaną fasolę do sosu i gotuj wszystko razem, aż smaki się połączą.",
        text12: "5. Serve the dish hot, ofter with bread.",
        title4: "Charakterystyka",
        text13: "• Jest to danie jednogarnkowe, którego głównymi składnikami są fasola, kiełbasa, boczek i sos pomidorowy.",
        text14: "• Jest to danie bardzo pożywne i rozgrzewające, dlatego też często pojawia się na polskich stołach w chłodniejsze dni.",
        text15: "• Pomimo nazwy, danie to nie ma nic wspólnego z Bretanią we Francji. Nazwa prawdopodobnie pochodzi od terminu „à la bretonne”, który w kuchni francuskiej oznacza potrawę z fasolą.",
      },
      CakeWithBeans: {
        title: "Ciastka Fasolowe",
        description: "Ten przepis jest inspirowany portugalskimi 'pastéis de feijão', ale dostosowany do bardziej przypominającego ciasto. Jest wilgotny, pyszny i zaskakująco zrobiony z białej fasoli!",
        title2: "Składniki",
        text: "• 1 (15 uncji) puszka fasoli cannellini, dokładnie wypłukanej i odsączonej",
        text2: "• 3 duże jajka",
        text3: "• 1/2 szklanki cukru granulowanego",
        text4: "• 1/4 szklanki niesolonego masła, roztopionego i ostudzonego",
        text5: "• 1 łyżeczka ekstraktu waniliowego",
        text6: "• 1/4 łyżeczki ekstraktu migdałowego",
        text7: "• 1/4 zmielonych migdałów",
        text8: "• 1/4 łyżeczki soli",
        text9: "• Cukier puder do posypania (opcjonalnie)",
        title3: "Instrukcje",
        text10: "1. Rozgrzej piekarnik do 175ºC (350ºF). Nasmaruj tłuszczem i oprósz mąką okrągłą formę do ciasta o średnicy 9 cali.",
        text11: "2. W robocie kuchennym lub blenderze wymieszaj fasolę, jajka, cukier, roztopione masło, ekstrakt waniliowy, ekstrakt migdałowy, zmielone migdały i sól. Miksuj do uzyskania całkowicie gładkiej masy.",
        text12: "3. Wlej ciasto do przygotowanej formy i piecz przez 30–35 minut, lub do momentu, aż wykałaczka włożona w środek ciasta będzie czysta.",
        title4: "Porady",
        text13: "• Aby uniknąć fasolowego posmaku, należy ją bardzo dokładnie odsączyć i opłukać.",
        text14: "• Fasolę cannellini możesz zastąpić innym rodzajem białej fasoli, np. fasolą amerykańską lub fasolą białą odmiany Great Northern.",
        text15: "• Jeśli nie masz zmielonych migdałów, możesz użyć mąki migdałowej lub drobno posiekanych migdałów.",
        text16: "• Podawaj ciasto z kleksem bitej śmietany lub gałką lodów.",
      },
      Borscht: {
        title: "Barszcz",
        description: "Barszcz z fasolą to ciekawa odmiana tradycyjnego barszczu, łącząca słodko-kwaśny smak buraków z sycącym dodatkiem fasoli.",
        title2: "Składniki (przykładowe):",
        text: "• Buraki",
        text2: "• Marchew",
        text3: "• Korzeń pietruszki",
        text4: "• Korzeń selera",
        text5: "• Cebula",
        text6: "• Czosnek",
        text7: "• Fasola (biała, czerwona lub pinto)",
        text8: "• Bulion warzywny",
        text9: "• Ocet lub sok z cytryny",
        text10: "• Cukier (opcjonalnie)",
        text11: "• Przyprawy (liść laurowy, ziele angielskie, pieprz, sól)",
        title3: "Instrukcje",
        text12: "1. Gotuj warzywa korzeniowe i buraki w bulionie, aż będą miękkie.",
        text13: "2. Ugotuj fasolę osobno lub dodaj ją do zupy pod koniec gotowania.",
        text14: "3. Zblenduj lub zetrzyj buraki i część warzyw.",
        text15: "4. Dodaj fasolę, ocet lub sok z cytryny, cukier (opcjonalnie) i przyprawy.",
        text16: "5. Gotuj jeszcze kilka minut, aby smaki się połączyły.",
        text17: "6. Podawaj z chlebem, ziemniakami lub innymi dodatkami.",
        title4: "Charakterystyka",
        text18: "• Barszcz z fasolą to zupa łącząca tradycyjne składniki barszczu (buraki, warzywa korzeniowe) z dodatkiem fasoli.",
        text19: "• Fasola dodaje gęstości, sytości i wartości odżywczych zupie.",
        text20: "• Może być podawana na gorąco lub na zimno, w zależności od preferencji.",
        text21: "• Jest to danie wegetariańskie lub wegańskie, w zależności od użytych składników (np. bulion warzywny)."
      },
      SourRyeSoup: {
        title: "Żurek",
        description: "Żurek to tradycyjna polska zupa na zakwasie żytnim. To sycące i charakterystyczne danie o unikalnym profilu smakowym.",
        title2: "Składniki",
        text: "• Polska kiełbasa",
        text2: "• Wędzony boczek lub szynka",
        text3: "• Ziemniaki",
        text4: "• Jajka na twardo",
        text5: "• Cebula i czosnek",
        text6: "• Majeranek i inne przyprawy",
        title3: "Charakterystyka",
        text7: "• Kwaśna baza: Główną cechą żurku jest jego kwaśna, fermentowana baza z mąki żytniej. Ten zakwas nadaje zupie charakterystyczną kwasowość.",
        text8: "• Odmiany: Istnieją regionalne odmiany żurku. Niektóre z nich mogą zawierać grzyby, chrzan lub inne dodatki.",
        text9: "• Znaczenie tradycyjne: Żurek często kojarzony jest z Wielkanocą w Polsce, kiedy to jest popularnym daniem podawanym podczas świąt. Jest również popularnym daniem na co dzień przez cały rok.",
        title4: "Sposób podania",
        text10: "• Żurek często podaje się w misce lub, bardziej tradycyjnie, w wydrążonym bochenku chleba.",
        text11: "• Zazwyczaj jest ozdobiony połówkami jajek na twardo i świeżymi ziołami."
      },

      discoverTitle: "Odkryj więcej o naszym regionie",
      discoverText: "Poznaj lokalne atrakcje, jedzenie, kulturę i życie społeczności w naszym mieście.",
    }
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, translations }
    }>
      {children}
    </LanguageContext.Provider >
  );
};

export const useLanguage = () => useContext(LanguageContext);